---
- name: "Ensure journal.conf is in the expected state"
  template:
    src: "etc/systemd/journald.conf.j2"
    dest: "/etc/systemd/journald.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  notify: "restart systemd-journald"
